dist: focal

language: go

go:
  - 1.22.x

services:
  - docker

# https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

env:
  - GO111MODULE=on

script:
  - make acceptance
